from django.core.management.base import BaseCommand
from products.models import ProductCategory, BeautyProduct

class Command(BaseCommand):
    help = "Seeds the database with exactly 50 curated beauty products across 5 categories."

    def handle(self, *args, **kwargs):
        self.stdout.write("Starting database seeding...")

        # 1. Create categories if they do not exist
        categories_to_seed = [
            ("Face Wash", "Cleansers to wash away dirt and excess sebum."),
            ("Moisturizer", "Creams and gels to lock in moisture and protect the skin barrier."),
            ("Sunscreen", "SPFs to protect against UV damage and pigmentation."),
            ("Serum", "Concentrated treatments for specific skin needs like brightness and hydration."),
            ("Eye Care", "Eye creams and serums targeting puffiness and dark circles."),
        ]

        categories = {}
        for name, desc in categories_to_seed:
            cat, created = ProductCategory.objects.get_or_create(
                name=name,
                defaults={"description": desc}
            )
            categories[name] = cat
            if created:
                self.stdout.write(self.style.SUCCESS(f"Created category: {name}"))
            else:
                self.stdout.write(f"Category already exists: {name}")

        # 2. Product Data lists
        products_data = [
            # --- FACE WASH PRODUCTS ---
            {
                "category": "Face Wash",
                "brand": "CeraVe",
                "name": "Foaming Facial Cleanser",
                "description": "Cleanses and removes oil without disrupting the protective skin barrier. Contains ceramides, hyaluronic acid, and niacinamide.",
                "suitable_skin_types": ["Oily", "Combination", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.7
            },
            {
                "category": "Face Wash",
                "brand": "Cetaphil",
                "name": "Gentle Skin Cleanser",
                "description": "A mild, non-irritating formula that softens as it cleanses. Ideal for dry, sensitive skin.",
                "suitable_skin_types": ["Dry", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.6
            },
            {
                "category": "Face Wash",
                "brand": "La Roche Posay",
                "name": "Effaclar Cleanser",
                "description": "Gently purifies oily skin without drying. Eliminates impurities and excess sebum.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": False,
                "price_range": "Premium",
                "rating": 4.5
            },
            {
                "category": "Face Wash",
                "brand": "Neutrogena",
                "name": "Oil Free Acne Wash",
                "description": "Salicylic acid acne treatment to help prevent breakouts. Clinically proven skin-soothing formula.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": False,
                "fragrance_free": False,
                "price_range": "Budget",
                "rating": 4.4
            },
            {
                "category": "Face Wash",
                "brand": "Bioderma",
                "name": "Sebium Gel",
                "description": "Gently cleanses and purifies without drying the skin. Limits sebum secretion and keeps pores clean.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.5
            },
            {
                "category": "Face Wash",
                "brand": "Simple",
                "name": "Refreshing Face Wash",
                "description": "Thoroughly washes away make-up, dirt and other impurities, leaving skin feeling clean, fresh and revived.",
                "suitable_skin_types": ["Normal", "Dry", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.5
            },
            {
                "category": "Face Wash",
                "brand": "The Face Shop",
                "name": "Rice Water Cleanser",
                "description": "Foaming cleanser that brightens the skin and removes impurities with rich whip cream texture.",
                "suitable_skin_types": ["Combination", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": False,
                "fragrance_free": False,
                "price_range": "Midrange",
                "rating": 4.4
            },
            {
                "category": "Face Wash",
                "brand": "Minimalist",
                "name": "Salicylic Acid Cleanser",
                "description": "LHA & Salicylic Acid cleanser that penetrates deep into pores to reduce sebum and fight acne breakouts.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.5
            },
            {
                "category": "Face Wash",
                "brand": "Avene",
                "name": "Cleanance Gel",
                "description": "Soap-free cleansing gel for acne-prone skin. Gently eliminates impurities and excess sebum.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.6
            },
            {
                "category": "Face Wash",
                "brand": "Cosrx",
                "name": "Low PH Good Morning Cleanser",
                "description": "Gently cleanses and exfoliates without stripping natural oils. Formulated with tea tree oil.",
                "suitable_skin_types": ["Combination", "Oily", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.6
            },

            # --- MOISTURIZERS ---
            {
                "category": "Moisturizer",
                "brand": "Neutrogena",
                "name": "Hydro Boost",
                "description": "A unique water gel moisturizer that absorbs quickly like a gel, but hydrates like a cream. Non-comedogenic.",
                "suitable_skin_types": ["Oily", "Combination", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.6
            },
            {
                "category": "Moisturizer",
                "brand": "CeraVe",
                "name": "Moisturizing Cream",
                "description": "Rich barrier protection cream with three essential ceramides. Provides 24-hour hydration.",
                "suitable_skin_types": ["Dry", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.8
            },
            {
                "category": "Moisturizer",
                "brand": "Cetaphil",
                "name": "Moisturizing Lotion",
                "description": "Lightweight hydration for sensitive or dry skin. Fast absorbing and non-greasy.",
                "suitable_skin_types": ["Dry", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.6
            },
            {
                "category": "Moisturizer",
                "brand": "Simple",
                "name": "Hydrating Moisturizer",
                "description": "Provides instant hydration and leaves skin feeling soft and smooth. Formulated with skin-loving ingredients.",
                "suitable_skin_types": ["Normal", "Combination", "Dry"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.5
            },
            {
                "category": "Moisturizer",
                "brand": "La Roche Posay",
                "name": "Toleriane Moisturizer",
                "description": "Prebiotic face moisturizer that helps restore the skin's protective barrier and provides long-lasting hydration.",
                "suitable_skin_types": ["Combination", "Normal", "Dry"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.6
            },
            {
                "category": "Moisturizer",
                "brand": "Bioderma",
                "name": "Atoderm Cream",
                "description": "Ultra-nourishing daily cream that strengthens the skin barrier and hydrates deeply.",
                "suitable_skin_types": ["Dry", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.5
            },
            {
                "category": "Moisturizer",
                "brand": "Minimalist",
                "name": "Sepicalm Moisturizer",
                "description": "A lightweight moisturizer with 3% Sepicalm to soothe redness and hydrate oily or combination skin.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.4
            },
            {
                "category": "Moisturizer",
                "brand": "Clinique",
                "name": "Moisture Surge",
                "description": "Oil-free gel-cream moisturizer provides hydration that lasts for 100 hours. Penetrates deep.",
                "suitable_skin_types": ["Combination", "Oily", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.7
            },
            {
                "category": "Moisturizer",
                "brand": "Avene",
                "name": "Hydrance Aqua Gel",
                "description": "All-in-one gel-cream hydrates, soothes, and detoxifies skin. Very refreshing.",
                "suitable_skin_types": ["Normal", "Dry", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.6
            },
            {
                "category": "Moisturizer",
                "brand": "Cosrx",
                "name": "Oil Free Moisturizer",
                "description": "Lotion type moisturizer formulated with 70% birch sap to soothe and treat irritated skin.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.5
            },

            # --- SUNSCREENS ---
            {
                "category": "Sunscreen",
                "brand": "La Roche Posay",
                "name": "Anthelios SPF 50",
                "description": "Lightweight, fluid sunscreen that offers high broad-spectrum protection. Matte finish.",
                "suitable_skin_types": ["Combination", "Oily", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.8
            },
            {
                "category": "Sunscreen",
                "brand": "Neutrogena",
                "name": "Ultra Sheer SPF 50",
                "description": "Dry-touch sunscreen formula absorbs quickly, leaving a clean, weightless, non-greasy feel.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": False,
                "fragrance_free": False,
                "price_range": "Budget",
                "rating": 4.4
            },
            {
                "category": "Sunscreen",
                "brand": "Bioderma",
                "name": "Photoderm SPF 50",
                "description": "Very high dermatological sun protection cream, activates natural skin defenses.",
                "suitable_skin_types": ["Dry", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.6
            },
            {
                "category": "Sunscreen",
                "brand": "Minimalist",
                "name": "SPF 50 Sunscreen",
                "description": "A light, multi-vitamin sunscreen that protects from UV rays and keeps skin nourished.",
                "suitable_skin_types": ["Combination", "Dry", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.5
            },
            {
                "category": "Sunscreen",
                "brand": "Reequil",
                "name": "Ultra Matte SPF 50",
                "description": "Silicone gel sunscreen provides a velvety matte finish, highly water and sweat resistant.",
                "suitable_skin_types": ["Oily", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.6
            },
            {
                "category": "Sunscreen",
                "brand": "Avene",
                "name": "SPF 50",
                "description": "Broad-spectrum protection mineral fluid, extremely water-resistant and suitable for dry skin.",
                "suitable_skin_types": ["Dry", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.5
            },
            {
                "category": "Sunscreen",
                "brand": "Cetaphil",
                "name": "Sun SPF 50",
                "description": "Liposomal formulation sunscreen, very easy to distribute. Nourishes with Vitamin E.",
                "suitable_skin_types": ["Combination", "Dry", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.4
            },
            {
                "category": "Sunscreen",
                "brand": "Fixderma",
                "name": "Shadow SPF 50",
                "description": "Non-greasy cream formulation specially designed to suit all skin types under sun exposure.",
                "suitable_skin_types": ["Normal", "Dry", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.3
            },
            {
                "category": "Sunscreen",
                "brand": "Isntree",
                "name": "Watery Sun Gel",
                "description": "Infused with active hyaluronic acid to keep skin moist, block UV rays, and leave no white cast.",
                "suitable_skin_types": ["Dry", "Combination", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.7
            },
            {
                "category": "Sunscreen",
                "brand": "Beauty of Joseon",
                "name": "Relief Sun",
                "description": "Organic sunscreen with rice extract and grain fermented extracts. Light and moist texture.",
                "suitable_skin_types": ["Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.8
            },

            # --- SERUMS ---
            {
                "category": "Serum",
                "brand": "The Ordinary",
                "name": "Niacinamide",
                "description": "High-strength vitamin and mineral blemish formula with 10% Niacinamide and 1% Zinc.",
                "suitable_skin_types": ["Oily", "Combination", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.5
            },
            {
                "category": "Serum",
                "brand": "The Ordinary",
                "name": "Vitamin C",
                "description": "Brightens the skin tone and reduces the visible signs of aging. Strong antioxidant.",
                "suitable_skin_types": ["Normal", "Dry", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": False,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.2
            },
            {
                "category": "Serum",
                "brand": "Minimalist",
                "name": "Niacinamide",
                "description": "Niacinamide serum helps clear blemishes, reduce sebum activity, and improve skin barrier.",
                "suitable_skin_types": ["Combination", "Oily", "Normal"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.5
            },
            {
                "category": "Serum",
                "brand": "Minimalist",
                "name": "Vitamin C",
                "description": "Ethyl Ascorbic Acid serum that brightens skin, reduces dullness, and targets hyperpigmentation.",
                "suitable_skin_types": ["Normal", "Dry", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.4
            },
            {
                "category": "Serum",
                "brand": "The Ordinary",
                "name": "Alpha Arbutin",
                "description": "Purified Alpha Arbutin helps reduce the appearance of dark spots and hyperpigmentation.",
                "suitable_skin_types": ["Normal", "Dry", "Combination", "Oily"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.4
            },
            {
                "category": "Serum",
                "brand": "Cosrx",
                "name": "Snail Mucin",
                "description": "Light-weight essence absorbs into skin fast, providing repair, hydration, and soothing relief.",
                "suitable_skin_types": ["Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.7
            },
            {
                "category": "Serum",
                "brand": "La Roche Posay",
                "name": "Vitamin C10",
                "description": "Pure vitamin C anti-aging serum reveals sensitive skin's full radiance, fades spots, and clarifies skin.",
                "suitable_skin_types": ["Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.6
            },
            {
                "category": "Serum",
                "brand": "The Ordinary",
                "name": "Hyaluronic Acid",
                "description": "A multi-depth hydration support formula containing 3 molecular weights of hyaluronic acid.",
                "suitable_skin_types": ["Dry", "Normal", "Combination", "Oily"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.6
            },
            {
                "category": "Serum",
                "brand": "Minimalist",
                "name": "Hyaluronic Acid",
                "description": "Concentrated hyaluronic acid serum with aloe juice to provide multi-level skin hydration.",
                "suitable_skin_types": ["Dry", "Normal", "Combination", "Oily"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.5
            },
            {
                "category": "Serum",
                "brand": "Beauty of Joseon",
                "name": "Glow Serum",
                "description": "Enriched with 60% propolis extract and 2% niacinamide to reduce sebum activity and brighten skin.",
                "suitable_skin_types": ["Oily", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": True,
                "pigmentation_friendly": True,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.6
            },

            # --- EYE CARE PRODUCTS ---
            {
                "category": "Eye Care",
                "brand": "The Ordinary",
                "name": "Caffeine Solution",
                "description": "Light-textured eye formulation reduces the appearance of eye contour pigmentation and puffiness.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.5
            },
            {
                "category": "Eye Care",
                "brand": "Minimalist",
                "name": "Eye Cream",
                "description": "Retinol and caffeine eye formulation to treat under-eye dark circles, shadows, and fine lines.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.3
            },
            {
                "category": "Eye Care",
                "brand": "Clinique",
                "name": "All About Eyes",
                "description": "Lightweight cream-gel diminishes the look of under-eye circles, shadows, and puffiness.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.6
            },
            {
                "category": "Eye Care",
                "brand": "CeraVe",
                "name": "Eye Repair Cream",
                "description": "Helps reduce the look of dark circles and puffiness. Contains essential ceramides and hyaluronic acid.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Budget",
                "rating": 4.4
            },
            {
                "category": "Eye Care",
                "brand": "La Roche Posay",
                "name": "Pigmentclar Eyes",
                "description": "Concentrated in Phe-Resorcinol and Caffeine to visibly reduce blue and brown dark circles.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.5
            },
            {
                "category": "Eye Care",
                "brand": "Avene",
                "name": "Eye Contour Cream",
                "description": "Soothing cream calms under-eye puffiness and targets dark circles. Extremely gentle.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Premium",
                "rating": 4.4
            },
            {
                "category": "Eye Care",
                "brand": "Bioderma",
                "name": "Sensibio Eye",
                "description": "Instantly soothes sensations of discomfort and irritation in the eye area. De-puffs under eyes.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.3
            },
            {
                "category": "Eye Care",
                "brand": "Innisfree",
                "name": "Green Tea Eye Cream",
                "description": "A hydrating roll-on eye cream formulated with beauty green tea and seed oil.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": False,
                "dark_circle_friendly": False,
                "sensitive_skin_safe": True,
                "fragrance_free": False,
                "price_range": "Budget",
                "rating": 4.2
            },
            {
                "category": "Eye Care",
                "brand": "Cosrx",
                "name": "Snail Eye Cream",
                "description": "Double functioning eye cream containing snail secretion filtrate to hydrate and brighten eyes.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.6
            },
            {
                "category": "Eye Care",
                "brand": "Beauty of Joseon",
                "name": "Eye Serum",
                "description": "Eye serum enriched with ginseng extract and retinal to treat dark circles and restore elasticity.",
                "suitable_skin_types": ["Oily", "Dry", "Normal", "Combination"],
                "suitable_skin_tones": ["Fair", "Light", "Medium", "Tan", "Deep"],
                "acne_friendly": False,
                "pigmentation_friendly": True,
                "dark_circle_friendly": True,
                "sensitive_skin_safe": True,
                "fragrance_free": True,
                "price_range": "Midrange",
                "rating": 4.7
            }
        ]

        # 3. Insert products using get_or_create to prevent duplicates
        success_count = 0
        duplicate_count = 0

        for prod_info in products_data:
            cat_name = prod_info.pop("category")
            cat_obj = categories[cat_name]
            
            # Use get_or_create identifying by name and brand
            product, created = BeautyProduct.objects.get_or_create(
                brand=prod_info["brand"],
                name=prod_info["name"],
                defaults={
                    "category": cat_obj,
                    "description": prod_info["description"],
                    "suitable_skin_types": prod_info["suitable_skin_types"],
                    "suitable_skin_tones": prod_info["suitable_skin_tones"],
                    "acne_friendly": prod_info["acne_friendly"],
                    "pigmentation_friendly": prod_info["pigmentation_friendly"],
                    "dark_circle_friendly": prod_info["dark_circle_friendly"],
                    "sensitive_skin_safe": prod_info["sensitive_skin_safe"],
                    "fragrance_free": prod_info["fragrance_free"],
                    "price_range": prod_info["price_range"],
                    "rating": prod_info["rating"],
                    "active": True
                }
            )

            if created:
                success_count += 1
                self.stdout.write(f"Product seeded: {product.brand} - {product.name}")
            else:
                duplicate_count += 1
                self.stdout.write(f"Product already exists (skipped): {product.brand} - {product.name}")

        self.stdout.write(self.style.SUCCESS(f"Seeding completed successfully: {success_count} products added, {duplicate_count} skipped."))
