# Generated by Django 6.0.6 on 2026-06-24 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_detected', models.BooleanField(default=False)),
                ('total_faces', models.IntegerField(default=0)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('landmarks', models.JSONField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_analyses', to='analysis.uploadedimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
