# Generated by Django 6.0.6 on 2026-06-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_faceanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceanalysis',
            name='face_shape',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='faceanalysis',
            name='face_shape_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
