# Generated by Django 6.0.6 on 2026-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_faceanalysis_face_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceanalysis',
            name='acne_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faceanalysis',
            name='acne_severity',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faceanalysis',
            name='dark_circle_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faceanalysis',
            name='pigmentation_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faceanalysis',
            name='skin_health_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceanalysis',
            name='skin_tone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faceanalysis',
            name='skin_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
