# Generated by Django 6.0.6 on 2026-06-26 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_faceanalysis_acne_detected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeardAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assets/beards/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assets/beards/thumbnails/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlassesAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assets/glasses/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assets/glasses/thumbnails/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HairStyleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('face_shape', models.CharField(default='All', max_length=50)),
                ('gender', models.CharField(default='Unisex', max_length=20)),
                ('length', models.CharField(default='Medium', max_length=50)),
                ('style', models.CharField(default='Casual', max_length=50)),
                ('image', models.ImageField(upload_to='assets/hairstyles/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assets/hairstyles/thumbnails/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TryOnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_color', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_image', models.ImageField(upload_to='tryon_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_histories', to='analysis.uploadedimage')),
                ('selected_beard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.beardasset')),
                ('selected_glasses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.glassesasset')),
                ('selected_hairstyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.hairstyleasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Try-On History',
                'verbose_name_plural': 'Try-On Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
