# Generated by Django 6.0.6 on 2026-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_beardasset_glassesasset_hairstyleasset_tryonhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonhistory',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
