# Generated by Django 6.0.6 on 2026-06-25 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0004_faceanalysis_acne_detected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='BeautyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('suitable_skin_types', models.JSONField(default=list, help_text="List of skin types, e.g., ['Oily', 'Dry']")),
                ('suitable_skin_tones', models.JSONField(default=list, help_text="List of skin tones, e.g., ['Fair', 'Medium']")),
                ('acne_friendly', models.BooleanField(default=False)),
                ('pigmentation_friendly', models.BooleanField(default=False)),
                ('dark_circle_friendly', models.BooleanField(default=False)),
                ('sensitive_skin_safe', models.BooleanField(default=False)),
                ('fragrance_free', models.BooleanField(default=False)),
                ('price_range', models.CharField(choices=[('Budget', 'Budget'), ('Midrange', 'Midrange'), ('Premium', 'Premium')], default='Midrange', max_length=20)),
                ('rating', models.FloatField(default=4.0)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations_json', models.JSONField(help_text='Detailed routine steps and category matching items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to='analysis.faceanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation History',
                'verbose_name_plural': 'Recommendation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('skin_type', models.CharField(choices=[('Oily', 'Oily'), ('Dry', 'Dry'), ('Normal', 'Normal'), ('Combination', 'Combination'), ('All', 'All')], default='All', max_length=20)),
                ('concern', models.CharField(choices=[('Acne', 'Acne'), ('Pigmentation', 'Pigmentation'), ('Dark Circles', 'Dark Circles'), ('None', 'None'), ('All', 'All')], default='All', max_length=50)),
                ('rule_type', models.CharField(choices=[('recommend', 'Recommend / Boost'), ('avoid', 'Avoid / Penalize')], default='recommend', max_length=20)),
                ('keyword', models.CharField(blank=True, help_text='Keyword in product name or description to match (case insensitive)', max_length=100)),
                ('score_modifier', models.IntegerField(default=0, help_text='Points to add or subtract (e.g. +10, -50)')),
                ('active', models.BooleanField(default=True)),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='products.productcategory')),
            ],
        ),
    ]
